title: RustFest.eu
email: team@rustfest.eu
description: >
  A Rust Community conference travelling all around Europe.

baseurl: "" # the subpath of the site, e.g. /blog
url: "http://www.rustfest.eu" # the base hostname & protocol for the site
metaKeywords: "rust, conf, rustfest, rustfesteu, conference, programming language"
social:
  twitter: rustfest
  github: rustfesteu
  facebook: rustfest
socialImageSrc: "/assets/favicons/logo.png"

location:
  venue: "TBD"
  city: "Paris"
  country: "France"
dates:
  year: "2018"
  talks: "Someday, Spring"
  workshops: "Someday, Spring"

# Page Settings
owner: "asquera Event UG"

collections:
  sessions:
    permalink: /:collection/:path
    output: true
  people:
    permalink: /:collection/:path
    output: true
  sponsors:
    permalink: /:collection/:path
    # They have their own link.
    output: false
  past_events:
    permalink: /:collection/:path
    # They have their own website!
    output: false

defaults:
  - scope:
      type: sessions
    values:
      layout: session
  - scope:
      type: people
    values:
      layout: person

# mailinglist
mailchimp:
  server: asquera.us13.list-manage.com
  user: 7945052bc1ecc432bff53c079
  id: 5929ff51d6

exclude: 
  - /vendor

# Build settings
markdown: kramdown

permalink: /blog/:title

# Plugins
plugins:
  - jekyll-redirect-from